### ISSUE TITLE
Which revision to use for rib-0.12

### ISSUE THREAD

**Issue by kakkun61** [srid/rib-sample#12]
I try to build rib-sample but this requires newer version of rib than one on Hackage.
Which revision should I use for rib-0.12?

I'm happy if there are release tags like “rib-0.12” etc.

**Comment by srid** [comment]
@kakkun61 You can use https://github.com/srid/rib-sample/commit/a28d0e31aea95d53ff4736bf596ca529096c2cf6

I'll tag that revision before closing this issue.

**Comment by srid** [comment]
Note: if you build with nix, it should use the right rib version always.

**Comment by kakkun61** [comment]
Thank you 😊

I'm using Windows though I think Nix is useful.

**Comment by srid** [comment]
1.0 is now released to Hackage, and `master` of this repo uses 1.0 now.
